### ISSUE TITLE
Undefined property notices when enabling module

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/views_natural_sort#2]
I  enabled the module from within admin/modules and got a ton of error messages as it attempted to rebuild the sort data. Hmm, actually looks like the same 2 errors a zillion times (1,274 times each to be exact).

```
Notice: Undefined property: File::$name in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
Notice: Undefined property: File::$mime in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
```

Help?

**Comment by leeksoup** [comment]
I have a fair bit of coding experience but little familiarity with this codebase. If you give me some pointers I could try to help with debugging and fixing this module.

**Comment by keiserjb** [comment]
It's strange, I just turned the module off on the site I'm using this in.  Then I turned it back on and it indexed without any notices.  I think there version there is the same version here.

**Comment by leeksoup** [comment]
Very strange. I just tried to do the same thing, but I am getting the same errors (and the same number of them) as before upon indexing.

Also, to keep the info here, I'm including the updates I first reported on the forum thread. (This all does work in Drupal.)

The "A" part of the alphabetical sorting does work (i.e. "A ..." and "An ..." at the beginning of book titles are not sorted under "A") but "T" still has all the titles that begin with "The."

A bigger problem. I allow the first letter to be passed to the View as a contextual filter, and the books beginning with "A ..." don't show up in the pages under the appropriate letters, _unless_ the second word also begins with "A". E.g. "An American Alphabet" _does_ appear on the "A" page, but  "A Boy and His Pony" doesn't show up on the "B" page, though it should. 

If there is _no_ contextual filter, the titles that begin with articles are present, and are even sorted in the correct places. 

So it seems something is wrong in the contextual filter handling.

Edited to delete incorrect item.

**Comment by leeksoup** [comment]
@keiserjb - The original issue occurs in the following code (with context):
```
foreach ($entity_ids as $entity_id) {
    $results = entity_load($entry_type['entity_type'], array($entity_id));
    $entity = reset($results);
    $field_name = $entry_type['field'];
    $data[] = array(
      'eid' => $entity_id,
      'entity_type' => $entry_type['entity_type'],
      'field' => $field_name,
      'delta' => 0,
      'content' => $entity->$field_name,  // errors at this line
    );
  }
```

So is it looking for a File::$name or File::$mime entity field but it doesn't exist? Or do you have any idea what's happening here? I would like to try to help, but have zero familiarity with this codebase. Help?

I'll report the contextual filter bug separately.

**Comment by keiserjb** [comment]
I'm guessing this is a difference between D7 and Backdrop.  I just haven't had time to get back to this.

**Comment by keiserjb** [comment]
I have an idea that I am trying out.  I've been curious which branch of the code you are using.  Is it 1.x or 2.x.  We need to be using the 2.x version that replaces all of the entity_get_info with entity_plus_get_info.  This also requires the Entity Plus module.  I think this may be the source of some of the problems experienced.

**Comment by keiserjb** [comment]
Maybe I'm not right about the function name, but I believe Entity Plus is required.

**Comment by keiserjb** [comment]
I'm still seeing the notice.  While annoying that it shows up in the log, the notice does not prevent the module from working, but it clearly needs to be fixed before this module is every released for Backdrop.  As far as the contextual filter goes.  That works in Drupal?  I'm seeing activity in the issue queue over there with similar problems.  Don't think it was ever resolved.

**Comment by keiserjb** [comment]
https://www.drupal.org/project/views_natural_sort/issues/2081751

**Comment by leeksoup** [comment]
How do I figure out what version of the module I'm using? I don't see a version in either the UI or in the module info file. I just did a git clone from the link you posted on the forum in your first response to my question.

I do have Entity Plus installed and enabled.

Huh, you're right about contextual filters. They _used to_ work in D7 a couple years ago. However, it's broken in the newer / latest releases. I don't know when that happened as I've been working on other projects for a long time. See this issue / comment for how it used to work: https://www.drupal.org/project/views_natural_sort/issues/2832868#comment-13619204

**Comment by leeksoup** [comment]
OK, so seeing [your comment](#issuecomment-1470097618), the code I have downloaded uses entity_get_info and not entity_plus_get_info. So I guess version 1.x. 

ETA: I just tried selecting the 2.x branch and downloading it again and it's identical to what I had before from the 1.x branch.

**Comment by keiserjb** [comment]
Once again the php notices you are seeing do not affect the performance of the sort.  They are only notices, not errors.

**Comment by leeksoup** [comment]
Yes, I got that, thanks. Was just trying to respond to your comments re using the right version.

**Comment by keiserjb** [comment]
I was wrong about the entity_plus_get_info.  It should be entity_get_info.

**Comment by leeksoup** [comment]
> I was wrong about the entity_plus_get_info. It should be entity_get_info.

OK, no problem. Looks like I was using the latest version fwiw.

**Comment by keiserjb** [comment]
I think they are the same now, just different numbers so it matched the Drupal version.

**Comment by keiserjb** [comment]
I have the same Notice: `Undefined property: stdClass::$mime in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 232 of /app/sites/all/modules/views_natural_sort/views_natural_sort.module).` after adding a file in a D7 demo site, so nothing is worse off.

**Comment by leeksoup** [comment]
Okay, weird. I haven't had to rebuild the index in D7 since installing the module, so something must have changed in the meanwhile.

I'll go report these issues over there and see if anyone is still maintaining it or at least can give me any pointers. Thanks.

**Comment by keiserjb** [comment]
I think I fixed the undefined index.

**Comment by leeksoup** [comment]
Great! I will clone and test it. Thanks.

**Comment by leeksoup** [comment]
Did you update the code here at the default branch? Because I re-cloned it and ran it and am still getting the same Undefined property errors.

**Comment by keiserjb** [comment]
No that is the point of a PR and a merge request. I probably will not merge this until it is resolved in Drupal.

**Comment by leeksoup** [comment]
Ah, OK. Can I get the new code to test it, or not?

**Comment by keiserjb** [comment]
Go to the pull request linked above. This is a one line change.

**Comment by keiserjb** [comment]
I moved the fix to line 244 and merged it.  Reopen if you still have the undefined index.
